{% set name = "trivy" %}
{% set version = "0.64.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/aquasecurity/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 95f958c5cf46e063660c241d022a57f99309208c9725d6031b048c9c414ecfa7

  # csaf_distribution licenses
  - url: https://raw.githubusercontent.com/gocsaf/csaf/refs/heads/main/LICENSES/Apache-2.0.txt
    sha256: 074e6e32c86a4c0ef8b3ed25b721ca23aca83df277cd88106ef7177c354615ff
  - url: https://raw.githubusercontent.com/gocsaf/csaf/refs/heads/main/LICENSES/BSD-3-Clause.txt
    sha256: 5a93d5831e1297ab10fe643e1a631e83be392896da14ee2951285a79012df69d
  - url: https://raw.githubusercontent.com/gocsaf/csaf/refs/heads/main/LICENSES/MIT.txt
    sha256: d9f773a3d8d9e023744b73a755efe6c83c7ddc36e181198c7711cbdd6a7633c2

  - url: https://raw.githubusercontent.com/xi2/xz/refs/heads/master/LICENSE
    sha256: 5c640056d513f276d56635af7a0bed81cb7eac02a31b6e56d40c416557a8d8ce

build:
  number: 0
  script:
    - go build -v -o $PREFIX/bin/ ./cmd/trivy ./cmd/trivy  # [not win]
    - go build -v -o %LIBRARY_BIN%\trivy.exe .\cmd\trivy  # [win]
    - go-licenses save ./cmd/trivy --save_path licenses --ignore github.com/aquasecurity/trivy --ignore github.com/csaf-poc/csaf_distribution --ignore modernc.org/mathutil --ignore github.com/gocsaf/csaf/v3/csaf --ignore github.com/gocsaf/csaf/v3/util --ignore github.com/xi2/xz
    - cp Apache-2.0.txt licenses
    - cp BSD-3-Clause.txt licenses
    - cp MIT.txt licenses
    - cp LICENSE licenses/LICENSE-mathutil

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - trivy --help

about:
  home: https://github.com/aquasecurity/trivy
  license: Apache-2.0
  license_file:
    - LICENSE
    - licenses/
  summary: Trivy is a comprehensive and versatile security scanner. Trivy has scanners that look for security issues, and targets where it can find those issues.
  doc_url: https://aquasecurity.github.io/trivy/

extra:
  recipe-maintainers:
    - mediocretech
    - fhoehle
